In [30]:
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, association_rules

Slip 6

In [31]:
transactions = [    ['Bread', 'Milk'],
                    ['Bread', 'Diaper', 'Beer', 'Eggs'],
                    ['Milk', 'Diaper', 'Beer', 'Coke'],
                    ['Bread', 'Milk', 'Diaper', 'Beer'],
                    ['Bread', 'Milk', 'Diaper', 'Coke']
                ]

te = TransactionEncoder()

te_array = te.fit(transactions).transform(transactions)     #   Categorical Values into Numerical Format

In [33]:
df = pd.DataFrame(te_array, columns = te.columns_)
df

    Beer  Bread   Coke  Diaper   Eggs   Milk
0  False   True  False   False  False   True
1   True   True  False    True   True  False
2   True  False   True    True  False   True
3   True   True  False    True  False   True
4  False   True   True    True  False   True

In [34]:
freq_items = apriori(df, min_support = 0.5, use_colnames = True)
freq_items

   support                    itemsets
0      0.6           frozenset({Beer})
1      0.8          frozenset({Bread})
2      0.8         frozenset({Diaper})
3      0.8           frozenset({Milk})
4      0.6   frozenset({Diaper, Beer})
5      0.6  frozenset({Diaper, Bread})
6      0.6    frozenset({Bread, Milk})
7      0.6   frozenset({Diaper, Milk})

In [35]:
rules = association_rules(freq_items, metric = 'support', min_threshold = 0.05)
rules = rules.sort_values(['support', 'confidence'], ascending = [False, False])

rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
1,frozenset({Beer}),frozenset({Diaper}),0.6,0.8,0.6,1.00,1.2500,1.0,0.12,inf,0.50,0.75,1.000,0.875
0,frozenset({Diaper}),frozenset({Beer}),0.8,0.6,0.6,0.75,1.2500,1.0,0.12,1.6,1.00,0.75,0.375,0.875
2,frozenset({Diaper}),frozenset({Bread}),0.8,0.8,0.6,0.75,0.9375,1.0,-0.04,0.8,-0.25,0.60,-0.250,0.750
3,frozenset({Bread}),frozenset({Diaper}),0.8,0.8,0.6,0.75,0.9375,1.0,-0.04,0.8,-0.25,0.60,-0.250,0.750
4,frozenset({Bread}),frozenset({Milk}),0.8,0.8,0.6,0.75,0.9375,1.0,-0.04,0.8,-0.25,0.60,-0.250,0.750
5,frozenset({Milk}),frozenset({Bread}),0.8,0.8,0.6,0.75,0.9375,1.0,-0.04,0.8,-0.25,0.60,-0.250,0.750
6,frozenset({Diaper}),frozenset({Milk}),0.8,0.8,0.6,0.75,0.9375,1.0,-0.04,0.8,-0.25,0.60,-0.250,0.750
7,frozenset({Milk}),frozenset({Diaper}),0.8,0.8,0.6,0.75,0.9375,1.0,-0.04,0.8,-0.25,0.60,-0.250,0.750