In [14]:
import pandas as pd
import numpy as np
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, association_rules

Slip 6

In [2]:
#   Create the following dataset in python & Convert the categorical values into numeric format.Apply
#   the apriori algorithm on the above dataset to generate the frequent itemsets and association rules. Repeat
#   the process with different min_sup values.

transactions = [    ['Bread', 'Milk'],
                    ['Bread', 'Diaper', 'Beer', 'Eggs'],
                    ['Milk', 'Diaper', 'Beer', 'Coke'],
                    ['Bread', 'Milk', 'Diaper', 'Beer'],
                    ['Bread', 'Milk', 'Diaper', 'Coke']
                ]

te = TransactionEncoder()

te_array = te.fit(transactions).transform(transactions)     #   Categorical Values into Numerical Format

In [3]:
df = pd.DataFrame(te_array, columns = te.columns_)
df

    Beer  Bread   Coke  Diaper   Eggs   Milk
0  False   True  False   False  False   True
1   True   True  False    True   True  False
2   True  False   True    True  False   True
3   True   True  False    True  False   True
4  False   True   True    True  False   True

In [4]:
freq_items = apriori(df, min_support = 0.5, use_colnames = True)    #   Apriori Algorithm
freq_items

   support                    itemsets
0      0.6           frozenset({Beer})
1      0.8          frozenset({Bread})
2      0.8         frozenset({Diaper})
3      0.8           frozenset({Milk})
4      0.6   frozenset({Beer, Diaper})
5      0.6  frozenset({Bread, Diaper})
6      0.6    frozenset({Milk, Bread})
7      0.6   frozenset({Milk, Diaper})

In [5]:
rules = association_rules(freq_items, metric = 'support', min_threshold = 0.05)     #   Association Rules
rules = rules.sort_values(['support', 'confidence'], ascending = [False, False])

rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,frozenset({Beer}),frozenset({Diaper}),0.6,0.8,0.6,1.00,1.2500,1.0,0.12,inf,0.50,0.75,1.000,0.875
1,frozenset({Diaper}),frozenset({Beer}),0.8,0.6,0.6,0.75,1.2500,1.0,0.12,1.6,1.00,0.75,0.375,0.875
2,frozenset({Bread}),frozenset({Diaper}),0.8,0.8,0.6,0.75,0.9375,1.0,-0.04,0.8,-0.25,0.60,-0.250,0.750
3,frozenset({Diaper}),frozenset({Bread}),0.8,0.8,0.6,0.75,0.9375,1.0,-0.04,0.8,-0.25,0.60,-0.250,0.750
4,frozenset({Milk}),frozenset({Bread}),0.8,0.8,0.6,0.75,0.9375,1.0,-0.04,0.8,-0.25,0.60,-0.250,0.750
5,frozenset({Bread}),frozenset({Milk}),0.8,0.8,0.6,0.75,0.9375,1.0,-0.04,0.8,-0.25,0.60,-0.250,0.750
6,frozenset({Milk}),frozenset({Diaper}),0.8,0.8,0.6,0.75,0.9375,1.0,-0.04,0.8,-0.25,0.60,-0.250,0.750
7,frozenset({Diaper}),frozenset({Milk}),0.8,0.8,0.6,0.75,0.9375,1.0,-0.04,0.8,-0.25,0.60,-0.250,0.750

In [27]:
#   Download the Market basket dataset. Write a python program to read the dataset and display its
#   information. Preprocess the data (drop null values etc.) Convert the categorical values into numeric
#   format. Apply the apriori algorithm on the above dataset to generate the frequent itemsets and association
#   rules.

data = pd.read_csv("market_basket.csv")

data.info()

<class 'pandas.DataFrame'>
RangeIndex: 7500 entries, 0 to 7499
Data columns (total 20 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   shrimp             7500 non-null   str
 1   almonds            5746 non-null   str
 2   avocado            4388 non-null   str
 3   vegetables mix     3344 non-null   str
 4   green grapes       2528 non-null   str
 5   whole weat flour   1863 non-null   str
 6   yams               1368 non-null   str
 7   cottage cheese     980 non-null    str
 8   energy drink       653 non-null    str
 9   tomato juice       394 non-null    str
 10  low fat yogurt     255 non-null    str
 11  green tea          153 non-null    str
 12  honey              86 non-null     str
 13  salad              46 non-null     str
 14  mineral water      24 non-null     str
 15  salmon             7 non-null      str
 16  antioxydant juice  3 non-null      str
 17  frozen smoothie    3 non-null      str
 18  spinach            2 non-null      str
 19  olive oil          0 non-null      float64
dtypes: float64(1), str(19)
memory usage: 1.1 MB

In [28]:
transactions = data.apply(lambda row: row.dropna().astype(str).tolist(), axis = 1).tolist()

te = TransactionEncoder()

te_array = te.fit(transactions).transform(transactions)

In [33]:
df = pd.DataFrame(te_array, columns = te.columns_)
df

,asparagus,almonds,antioxydant juice,asparagus,avocado,babies food,bacon,barbecue sauce,black tea,blueberries,...,turkey,vegetables mix,water spray,white wine,whole weat flour,whole wheat pasta,whole wheat rice,yams,yogurt cake,zucchini
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,True,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7495,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7496,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7497,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7498,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7499,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False

In [34]:
freq_items = apriori(df, min_support = 0.5, use_colnames = True)
freq_items

Empty DataFrame
Columns: [support, itemsets]
Index: []