In [ ]:
import pandas as pd
import numpy as np
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, association_rules

Slip 6

In [86]:
#   Create the following dataset in python & Convert the categorical values into numeric format.Apply
#   the apriori algorithm on the above dataset to generate the frequent itemsets and association rules. Repeat
#   the process with different min_sup values.

transactions = [    ['Bread', 'Milk'],
                    ['Bread', 'Diaper', 'Beer', 'Eggs'],
                    ['Milk', 'Diaper', 'Beer', 'Coke'],
                    ['Bread', 'Milk', 'Diaper', 'Beer'],
                    ['Bread', 'Milk', 'Diaper', 'Coke']
                ]

te = TransactionEncoder()

te_array = te.fit(transactions).transform(transactions)     #   Categorical Values into Numerical Format

In [87]:
df = pd.DataFrame(te_array, columns = te.columns_)
df

    Beer  Bread   Coke  Diaper   Eggs   Milk
0  False   True  False   False  False   True
1   True   True  False    True   True  False
2   True  False   True    True  False   True
3   True   True  False    True  False   True
4  False   True   True    True  False   True

In [4]:
freq_items = apriori(df, min_support = 0.5, use_colnames = True)    #   Apriori Algorithm
freq_items

   support                    itemsets
0      0.6           frozenset({Beer})
1      0.8          frozenset({Bread})
2      0.8         frozenset({Diaper})
3      0.8           frozenset({Milk})
4      0.6   frozenset({Beer, Diaper})
5      0.6  frozenset({Bread, Diaper})
6      0.6    frozenset({Milk, Bread})
7      0.6   frozenset({Milk, Diaper})

In [ ]:
rules = association_rules(freq_items, metric = 'support', min_threshold = 0.05)     #   Association Rules

rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,frozenset({Beer}),frozenset({Diaper}),0.6,0.8,0.6,1.00,1.2500,1.0,0.12,inf,0.50,0.75,1.000,0.875
1,frozenset({Diaper}),frozenset({Beer}),0.8,0.6,0.6,0.75,1.2500,1.0,0.12,1.6,1.00,0.75,0.375,0.875
2,frozenset({Bread}),frozenset({Diaper}),0.8,0.8,0.6,0.75,0.9375,1.0,-0.04,0.8,-0.25,0.60,-0.250,0.750
3,frozenset({Diaper}),frozenset({Bread}),0.8,0.8,0.6,0.75,0.9375,1.0,-0.04,0.8,-0.25,0.60,-0.250,0.750
4,frozenset({Milk}),frozenset({Bread}),0.8,0.8,0.6,0.75,0.9375,1.0,-0.04,0.8,-0.25,0.60,-0.250,0.750
5,frozenset({Bread}),frozenset({Milk}),0.8,0.8,0.6,0.75,0.9375,1.0,-0.04,0.8,-0.25,0.60,-0.250,0.750
6,frozenset({Milk}),frozenset({Diaper}),0.8,0.8,0.6,0.75,0.9375,1.0,-0.04,0.8,-0.25,0.60,-0.250,0.750
7,frozenset({Diaper}),frozenset({Milk}),0.8,0.8,0.6,0.75,0.9375,1.0,-0.04,0.8,-0.25,0.60,-0.250,0.750

Slip 7

In [29]:
#   Download the Market basket dataset. Write a python program to read the dataset and display its
#   information. Preprocess the data (drop null values etc.) Convert the categorical values into numeric
#   format. Apply the apriori algorithm on the above dataset to generate the frequent itemsets and association
#   rules.

data = pd.read_csv("market_basket.csv")

data.info()

<class 'pandas.DataFrame'>
RangeIndex: 7500 entries, 0 to 7499
Data columns (total 20 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   shrimp             7500 non-null   str
 1   almonds            5746 non-null   str
 2   avocado            4388 non-null   str
 3   vegetables mix     3344 non-null   str
 4   green grapes       2528 non-null   str
 5   whole weat flour   1863 non-null   str
 6   yams               1368 non-null   str
 7   cottage cheese     980 non-null    str
 8   energy drink       653 non-null    str
 9   tomato juice       394 non-null    str
 10  low fat yogurt     255 non-null    str
 11  green tea          153 non-null    str
 12  honey              86 non-null     str
 13  salad              46 non-null     str
 14  mineral water      24 non-null     str
 15  salmon             7 non-null      str
 16  antioxydant juice  3 non-null      str
 17  frozen smoothie    3 non-null      str
 18  spinach            2 non-null      str
 19  olive oil          0 non-null      float64
dtypes: float64(1), str(19)
memory usage: 1.1 MB

In [30]:
transactions = []

for i in range(len(data)):
    row_item = []
    for j in range(len(data.columns)):
        val = data.values[i, j]
        if pd.notnull(val) and val != "":
            row_item.append(val)
    if len(row_item) > 0:
        transactions.append(row_item)

transactions

[['burgers', 'meatballs', 'eggs'],
 ['chutney'],
 ['turkey', 'avocado'],
 ['mineral water', 'milk', 'energy bar', 'whole wheat rice', 'green tea'],
 ['low fat yogurt'],
 ['whole wheat pasta', 'french fries'],
 ['soup', 'light cream', 'shallot'],
 ['frozen vegetables', 'spaghetti', 'green tea'],
 ['french fries'],
 ['eggs', 'pet food'],
 ['cookies'],
 ['turkey', 'burgers', 'mineral water', 'eggs', 'cooking oil'],
 ['spaghetti', 'champagne', 'cookies'],
 ['mineral water', 'salmon'],
 ['mineral water'],
 ['shrimp',
  'chocolate',
  'chicken',
  'honey',
  'oil',
  'cooking oil',
  'low fat yogurt'],
 ['turkey', 'eggs'],
 ['turkey',
  'fresh tuna',
  'tomatoes',
  'spaghetti',
  'mineral water',
  'black tea',
  'salmon',
  'eggs',
  'chicken',
  'extra dark chocolate'],
 ['meatballs', 'milk', 'honey', 'french fries', 'protein bar'],
 ['red wine', 'shrimp', 'pasta', 'pepper', 'eggs', 'chocolate', 'shampoo'],
 ['rice', 'sparkling water'],
 ['spaghetti', 'mineral water', 'ham', 'body spray', 'pancakes', 'green tea'],
 ['burgers',
  'grated cheese',
  'shrimp',
  'pasta',
  'avocado',
  'honey',
  'white wine',
  'toothpaste'],
 ['eggs'],
 ['parmesan cheese', 'spaghetti', 'soup', 'avocado', 'milk', 'fresh bread'],
 ['ground beef',
  'spaghetti',
  'mineral water',
  'milk',
  'energy bar',
  'black tea',
  'salmon',
  'frozen smoothie',
  'escalope'],
 ['sparkling water'],
 ['mineral water', 'eggs', 'chicken', 'chocolate', 'french fries'],
 ['frozen vegetables', 'spaghetti', 'yams', 'mineral water'],
 ['herb & pepper', 'tomato sauce', 'light cream', 'magazines'],
 ['mineral water', 'chocolate', 'avocado', 'eggs'],
 ['turkey', 'french fries', 'strawberries'],
 ['frozen vegetables', 'strong cheese', 'chocolate'],
 ['cookies'],
 ['pickles', 'spaghetti', 'salmon', 'escalope'],
 ['energy bar', 'french fries'],
 ['red wine', 'ground beef', 'mineral water'],
 ['mineral water', 'cake', 'cottage cheese'],
 ['pickles', 'champagne', 'green tea'],
 ['spaghetti'],
 ['fresh tuna',
  'frozen vegetables',
  'spaghetti',
  'mineral water',
  'honey',
  'whole wheat rice',
  'frozen smoothie',
  'escalope'],
 ['spaghetti'],
 ['soup', 'meatballs', 'hot dogs', 'sparkling water'],
 ['escalope'],
 ['soup',
  'avocado',
  'french fries',
  'hot dogs',
  'brownies',
  'body spray',
  'pancakes',
  'green tea'],
 ['mineral water', 'chicken', 'cereals', 'clothes accessories'],
 ['mineral water', 'bug spray'],
 ['avocado', 'muffins'],
 ['burgers', 'black tea', 'green tea'],
 ['spaghetti', 'chocolate', 'brownies', 'white wine', 'green tea'],
 ['fresh tuna', 'mineral water', 'eggs'],
 ['spaghetti', 'muffins'],
 ['spaghetti', 'chocolate'],
 ['french fries', 'escalope', 'champagne'],
 ['tomato sauce', 'light mayo'],
 ['turkey',
  'fresh tuna',
  'frozen vegetables',
  'tomatoes',
  'ground beef',
  'spaghetti',
  'mineral water',
  'chocolate',
  'soup',
  'milk',
  'olive oil'],
 ['eggs', 'cookies'],
 ['soup',
  'chicken',
  'gums',
  'soda',
  'body spray',
  'energy drink',
  'green tea'],
 ['turkey',
  'frozen vegetables',
  'mineral water',
  'cider',
  'cooking oil',
  'green tea'],
 ['spaghetti'],
 ['clothes accessories'],
 ['energy drink'],
 ['soup', 'bug spray', 'shallot', 'protein bar', 'green tea'],
 ['turkey', 'eggs'],
 ['french fries'],
 ['chocolate', 'milk'],
 ['herb & pepper',
  'whole wheat pasta',
  'ground beef',
  'mineral water',
  'avocado',
  'cider',
  'whole wheat rice'],
 ['cookies'],
 ['shrimp', 'pasta'],
 ['grated cheese', 'herb & pepper', 'tomatoes', 'tomato sauce', 'corn'],
 ['burgers', 'escalope', 'shallot'],
 ['cookies'],
 ['yogurt cake'],
 ['soup', 'eggs'],
 ['cookies'],
 ['mineral water', 'chocolate', 'low fat yogurt'],
 ['eggs', 'strawberries'],
 ['grated cheese', 'ground beef', 'spaghetti', 'mineral water', 'white wine'],
 ['mint'],
 ['eggs', 'cake', 'french fries'],
 ['burgers', 'spaghetti', 'milk', 'french fries', 'green tea'],
 ['mineral water', 'energy bar', 'butter', 'french fries'],
 ['burgers',
  'grated cheese',
  'herb & pepper',
  'mineral water',
  'eggs',
  'cooking oil'],
 ['energy bar'],
 ['energy bar', 'energy drink'],
 ['chocolate', 'frozen smoothie'],
 ['low fat yogurt'],
 ['asparagus', 'salad'],
 ['burgers', 'french fries', 'low fat yogurt', 'green tea'],
 ['low fat yogurt'],
 ['burgers',
  'herb & pepper',
  'shrimp',
  'pasta',
  'spaghetti',
  'mineral water',
  'meatballs',
  'olive oil',
  'energy bar',
  'french wine',
  'eggs',
  'salt'],
 ['champagne', 'low fat yogurt'],
 ['champagne'],
 ['burgers', 'almonds', 'eggs', 'french fries', 'cookies', 'green tea'],
 ['ham', 'soup', 'escalope', 'body spray'],
 ['turkey',
  'ham',
  'frozen vegetables',
  'pepper',
  'oil',
  'extra dark chocolate',
  'tea',
  'magazines'],
 ['muffins', 'eggs', 'cookies'],
 ['cookies'],
 ['frozen vegetables',
  'whole wheat pasta',
  'ground beef',
  'spaghetti',
  'chocolate',
  'green tea'],
 ['mineral water', 'barbecue sauce', 'chocolate'],
 ['burgers',
  'herb & pepper',
  'energy bar',
  'almonds',
  'eggs',
  'corn',
  'mayonnaise',
  'zucchini'],
 ['turkey',
  'burgers',
  'ground beef',
  'chocolate',
  'soup',
  'almonds',
  'eggs',
  'hot dogs',
  'cottage cheese'],
 ['ham', 'spaghetti', 'chocolate', 'eggs'],
 ['ground beef', 'energy bar', 'pet food', 'carrots', 'protein bar'],
 ['ground beef',
  'tomato sauce',
  'spaghetti',
  'mineral water',
  'almonds',
  'eggs'],
 ['mineral water', 'olive oil', 'gums', 'cooking oil'],
 ['shrimp',
  'pasta',
  'mineral water',
  'soup',
  'avocado',
  'milk',
  'olive oil',
  'green grapes',
  'eggs',
  'bug spray'],
 ['shrimp',
  'pasta',
  'soup',
  'cake',
  'cooking oil',
  'chicken',
  'light mayo',
  'low fat yogurt'],
 ['spaghetti',
  'mineral water',
  'chocolate',
  'french fries',
  'champagne',
  'escalope',
  'mushroom cream sauce',
  'fresh bread'],
 ['shrimp', 'pasta', 'mineral water', 'eggs'],
 ['burgers', 'oil', 'tomato juice', 'fresh bread'],
 ['french wine', 'eggs', 'chocolate', 'low fat yogurt'],
 ['chicken', 'eggs', 'french fries', 'pancakes'],
 ['turkey', 'herb & pepper', 'salmon', 'white wine', 'candy bars'],
 ['grated cheese',
  'spaghetti',
  'olive oil',
  'eggs',
  'french fries',
  'green tea'],
 ['mineral water', 'energy bar'],
 ['eggs', 'french fries'],
 ['burgers',
  'tomatoes',
  'mineral water',
  'soup',
  'milk',
  'almonds',
  'eggs',
  'chocolate',
  'tomato juice'],
 ['muffins'],
 ['pasta'],
 ['tomatoes', 'spaghetti', 'frozen smoothie'],
 ['ground beef', 'spaghetti', 'milk'],
 ['french fries'],
 ['chocolate', 'milk'],
 ['burgers',
  'shrimp',
  'pasta',
  'frozen vegetables',
  'spaghetti',
  'mineral water',
  'milk',
  'eggs',
  'chocolate',
  'french fries',
  'pancakes',
  'low fat yogurt'],
 ['ground beef', 'mineral water', 'antioxydant juice', 'protein bar'],
 ['grated cheese',
  'whole wheat pasta',
  'ground beef',
  'spaghetti',
  'cake',
  'energy drink'],
 ['grated cheese'],
 ['pancakes'],
 ['frozen smoothie'],
 ['carrots', 'green tea'],
 ['chocolate'],
 ['turkey',
  'burgers',
  'chocolate',
  'olive oil',
  'eggs',
  'cooking oil',
  'corn'],
 ['frozen vegetables',
  'tomatoes',
  'pepper',
  'spaghetti',
  'mineral water',
  'pancakes',
  'chicken',
  'chili',
  'tea',
  'french fries',
  'tomato juice',
  'fresh bread'],
 ['cookies'],
 ['ground beef'],
 ['turkey', 'eggs', 'chocolate', 'frozen smoothie', 'tomato juice'],
 ['frozen vegetables', 'cooking oil', 'mashed potato'],
 ['frozen vegetables',
  'ground beef',
  'tomato sauce',
  'mineral water',
  'meatballs',
  'olive oil',
  'light cream',
  'tomato juice'],
 ['red wine',
  'spaghetti',
  'mineral water',
  'soup',
  'milk',
  'eggs',
  'cake',
  'gums',
  'cooking oil',
  'chocolate',
  'frozen smoothie'],
 ['chocolate',
  'tomatoes',
  'spaghetti',
  'mineral water',
  'avocado',
  'milk',
  'olive oil',
  'eggs',
  'rice',
  'french fries',
  'brownies'],
 ['chocolate',
  'shrimp',
  'pasta',
  'frozen vegetables',
  'ground beef',
  'mineral water',
  'nonfat milk',
  'eggs'],
 ['turkey',
  'shrimp',
  'pasta',
  'pepper',
  'spaghetti',
  'mineral water',
  'eggs',
  'chicken',
  'french fries'],
 ['cookies'],
 ['turkey', 'tomatoes', 'cake'],
 ['yams',
  'mineral water',
  'soup',
  'milk',
  'pancakes',
  'whole wheat rice',
  'barbecue sauce',
  'carrots',
  'chocolate',
  'champagne'],
 ['rice'],
 ['chocolate', 'milk'],
 ['shrimp', 'pasta', 'frozen vegetables', 'water spray'],
 ['burgers', 'mineral water', 'milk', 'eggs', 'whole wheat rice', 'mint'],
 ['mineral water', 'vegetables mix', 'cake', 'frozen smoothie', 'brownies'],
 ['cookies'],
 ['shrimp', 'pasta', 'chicken', 'chocolate bread'],
 ['shallot'],
 ['shrimp', 'pasta', 'spaghetti', 'eggs', 'hot dogs', 'green tea'],
 ['burgers'],
 ['red wine',
  'ground beef',
  'spaghetti',
  'mineral water',
  'milk',
  'olive oil',
  'strong cheese',
  'light cream',
  'cooking oil'],
 ['burgers',
  'grated cheese',
  'spaghetti',
  'avocado',
  'milk',
  'oil',
  'french fries'],
 ['herb & pepper',
  'whole wheat pasta',
  'ground beef',
  'mineral water',
  'olive oil'],
 ['shrimp', 'pasta', 'yams', 'milk', 'chocolate'],
 ['butter', 'green tea'],
 ['light mayo'],
 ['low fat yogurt'],
 ['herb & pepper', 'shrimp', 'pasta', 'spaghetti', 'milk'],
 ['burgers', 'eggs'],
 ['turkey',
  'herb & pepper',
  'ground beef',
  'soup',
  'avocado',
  'milk',
  'black tea',
  'eggs',
  'barbecue sauce',
  'carrots',
  'cookies',
  'tomato juice',
  'fresh bread'],
 ['cookies'],
 ['escalope'],
 ['pepper', 'french fries', 'strawberries', 'pancakes', 'low fat yogurt'],
 ['frozen vegetables', 'yams', 'chicken', 'honey', 'light mayo'],
 ['chocolate', 'champagne'],
 ['herb & pepper', 'honey', 'cake', 'rice', 'protein bar'],
 ['burgers',
  'chocolate',
  'frozen vegetables',
  'ground beef',
  'mineral water',
  'milk',
  'light mayo',
  'asparagus'],
 ['chocolate', 'mineral water', 'corn', 'cottage cheese', 'green tea'],
 ['muffins'],
 ['ham', 'french wine', 'escalope'],
 ['spaghetti', 'milk', 'whole wheat rice', 'mint green tea'],
 ['chocolate', 'body spray'],
 ['frozen vegetables', 'french fries', 'hot dogs'],
 ['candy bars'],
 ['burgers',
  'shrimp',
  'pasta',
  'milk',
  'green tea',
  'french fries',
  'cookies',
  'white wine'],
 ['parmesan cheese', 'ground beef'],
 ['pancakes', 'whole wheat rice', 'candy bars'],
 ['eggs', 'eggplant', 'cookies'],
 ['frozen vegetables', 'mineral water'],
 ['chocolate'],
 ['turkey', 'spaghetti', 'milk', 'whole wheat rice', 'chocolate'],
 ['whole wheat pasta',
  'ground beef',
  'spaghetti',
  'soup',
  'meatballs',
  'chicken',
  'blueberries',
  'cooking oil',
  'champagne',
  'yogurt cake',
  'protein bar'],
 ['cooking oil', 'tomato juice'],
 ['frozen vegetables', 'milk', 'eggs', 'french fries', 'green tea'],
 ['fresh tuna',
  'spaghetti',
  'olive oil',
  'french wine',
  'eggs',
  'french fries',
  'champagne',
  'pancakes',
  'light mayo'],
 ['red wine', 'honey', 'hot dogs'],
 ['milk', 'bacon', 'eggs', 'french fries', 'fresh bread'],
 ['french fries', 'yogurt cake'],
 ['milk'],
 ['french fries'],
 ['chocolate'],
 ['burgers', 'ham', 'red wine'],
 ['shrimp',
  'pasta',
  'tomatoes',
  'energy bar',
  'french wine',
  'antioxydant juice',
  'french fries',
  'frozen smoothie',
  'brownies'],
 ['green tea'],
 ['low fat yogurt'],
 ['turkey',
  'spaghetti',
  'mineral water',
  'soup',
  'spinach',
  'soda',
  'energy drink',
  'salt'],
 ['turkey', 'eggs'],
 ['bug spray', 'hot dogs'],
 ['oil'],
 ['soup',
  'energy bar',
  'chicken',
  'eggs',
  'cake',
  'french fries',
  'body spray',
  'strawberries'],
 ['spaghetti', 'chocolate', 'yogurt cake'],
 ['turkey', 'mineral water', 'meatballs'],
 ['ground beef',
  'mineral water',
  'chocolate',
  'fromage blanc',
  'bacon',
  'hot dogs'],
 ['frozen vegetables', 'mineral water', 'vegetables mix', 'escalope'],
 ['herb & pepper', 'red wine', 'tomatoes'],
 ['whole wheat pasta', 'olive oil', 'cereals', 'brownies', 'green tea'],
 ['cookies'],
 ['olive oil', 'cookies', 'mushroom cream sauce'],
 ['ground beef', 'pancakes', 'cooking oil', 'gluten free bar', 'light mayo'],
 ['mineral water', 'french fries'],
 ['herb & pepper'],
 ['salmon'],
 ['eggs', 'escalope'],
 ['mineral water', 'tomato juice'],
 ['mineral water'],
 ['shrimp', 'mineral water', 'soup', 'black tea'],
 ['cake', 'frozen smoothie'],
 ['turkey',
  'burgers',
  'grated cheese',
  'tomatoes',
  'chocolate',
  'fromage blanc',
  'honey',
  'whole wheat rice'],
 ['frozen vegetables',
  'ground beef',
  'mineral water',
  'olive oil',
  'pancakes'],
 ['turkey',
  'burgers',
  'ground beef',
  'milk',
  'olive oil',
  'cake',
  'fresh bread'],
 ['whole wheat pasta',
  'ground beef',
  'spaghetti',
  'yams',
  'mineral water',
  'soup',
  'chutney',
  'cereals',
  'energy drink',
  'protein bar'],
 ['eggs', 'whole wheat rice', 'cake', 'green tea', 'escalope'],
 ['ground beef', 'yams', 'soup', 'avocado', 'salmon', 'green tea'],
 ['milk'],
 ['spaghetti', 'chocolate'],
 ['whole wheat pasta', 'honey'],
 ['whole wheat pasta', 'green tea'],
 ['spaghetti', 'meatballs', 'vegetables mix', 'chocolate'],
 ['eggs', 'low fat yogurt'],
 ['fresh tuna',
  'shrimp',
  'pasta',
  'mineral water',
  'olive oil',
  'eggs',
  'cake',
  'brownies',
  'tomato juice'],
 ['mineral water', 'green grapes', 'hot dogs', 'fresh bread'],
 ['frozen vegetables', 'meatballs', 'eggs', 'chocolate'],
 ['chocolate'],
 ['meatballs', 'milk'],
 ['low fat yogurt'],
 ['green tea'],
 ['escalope', 'pasta'],
 ['pepper',
  'chocolate',
  'olive oil',
  'french wine',
  'salmon',
  'rice',
  'light mayo',
  'fresh bread',
  'magazines'],
 ['red wine',
  'french wine',
  'vegetables mix',
  'rice',
  'clothes accessories',
  'hot dogs',
  'green tea'],
 ['burgers',
  'dessert wine',
  'spaghetti',
  'chicken',
  'cake',
  'protein bar',
  'green tea'],
 ['french wine', 'cake', 'fresh bread'],
 ['burgers', 'frozen vegetables', 'flax seed', 'eggs'],
 ['red wine'],
 ['pepper', 'mineral water', 'energy bar', 'green grapes'],
 ['milk', 'eggs', 'cake', 'chocolate', 'french fries', 'green tea'],
 ['french fries'],
 ['almonds'],
 ['burgers', 'mineral water', 'green tea'],
 ['milk', 'pancakes'],
 ['pancakes', 'eggs', 'salt', 'tomato juice'],
 ['mineral water'],
 ['ham', 'spaghetti', 'mineral water', 'olive oil'],
 ['salt', 'tomato juice', 'fresh bread'],
 ['spaghetti', 'mushroom cream sauce'],
 ['spaghetti', 'mineral water', 'eggs', 'pet food'],
 ['frozen vegetables', 'spaghetti'],
 ['energy drink'],
 ['muffins'],
 ['turkey', 'milk'],
 ['cookies'],
 ['chocolate'],
 ['spaghetti',
  'mineral water',
  'eggs',
  'cooking oil',
  'chocolate',
  'escalope'],
 ['shrimp', 'frozen vegetables', 'pepper', 'spaghetti', 'green tea'],
 ['burgers',
  'fresh tuna',
  'red wine',
  'mineral water',
  'french fries',
  'hand protein bar',
  'low fat yogurt'],
 ['pancakes', 'eggs', 'energy drink', 'fresh bread'],
 ['strong cheese',
  'salmon',
  'green tea',
  'french fries',
  'frozen smoothie',
  'hot dogs'],
 ['grated cheese',
  'shrimp',
  'pasta',
  'tomatoes',
  'milk',
  'frozen smoothie',
  'sandwich'],
 ['herb & pepper', 'whole wheat pasta', 'olive oil', 'pancakes', 'eggs'],
 ['spaghetti', 'antioxydant juice'],
 ['chocolate', 'milk', 'almonds', 'eggs', 'strawberries', 'white wine'],
 ['french fries', 'strawberries'],
 ['mineral water'],
 ['eggs'],
 ['escalope'],
 ['cake'],
 ['whole wheat pasta', 'antioxydant juice', 'body spray', 'green tea'],
 ['mineral water', 'oil', 'frozen smoothie'],
 ['french fries', 'champagne'],
 ['chocolate', 'french fries'],
 ['frozen vegetables', 'spaghetti', 'eggs'],
 ['hot dogs'],
 ['chocolate', 'cookies'],
 ['pancakes'],
 ['shrimp', 'butter', 'chicken', 'salmon'],
 ['chocolate', 'cookies', 'babies food'],
 ['pepper', 'spaghetti', 'cake', 'chocolate', 'french fries', 'fresh bread'],
 ['avocado', 'oil', 'cereals', 'french fries'],
 ['herb & pepper',
  'spaghetti',
  'mineral water',
  'spinach',
  'eggs',
  'oil',
  'cooking oil',
  'green tea',
  'shampoo',
  'tomato juice',
  'low fat yogurt'],
 ['herb & pepper',
  'frozen vegetables',
  'ground beef',
  'pepper',
  'spaghetti',
  'mint green tea',
  'french fries'],
 ['french fries'],
 ['green tea', 'tomato juice'],
 ['eggs', 'whole wheat rice', 'chocolate'],
 ['grated cheese',
  'herb & pepper',
  'red wine',
  'spaghetti',
  'mineral water',
  'salmon',
  'eggs',
  'cooking oil',
  'green tea'],
 ['french fries',
  'cookies',
  'shallot',
  'tomato juice',
  'fresh bread',
  'low fat yogurt'],
 ['burgers', 'fresh tuna', 'spaghetti', 'muffins', 'honey'],
 ['herb & pepper', 'ground beef', 'spaghetti', 'eggs', 'chicken'],
 ['grated cheese', 'muffins', 'tomato juice', 'mayonnaise'],
 ['whole wheat pasta',
  'yams',
  'mineral water',
  'muffins',
  'frozen smoothie',
  'hot dogs',
  'energy drink'],
 ['burgers',
  'spaghetti',
  'soup',
  'milk',
  'olive oil',
  'salmon',
  'eggs',
  'blueberries'],
 ['chocolate', 'champagne', 'magazines'],
 ['frozen vegetables',
  'spaghetti',
  'yams',
  'mineral water',
  'french wine',
  'green grapes',
  'rice',
  'chocolate'],
 ['tomato sauce', 'chocolate'],
 ['milk', 'eggs'],
 ['pet food'],
 ['yogurt cake'],
 ['green tea'],
 ['escalope', 'pasta'],
 ['herb & pepper', 'ground beef'],
 ['mineral water', 'honey', 'brownies'],
 ['turkey', 'eggs', 'cake', 'energy drink'],
 ['turkey',
  'burgers',
  'dessert wine',
  'ground beef',
  'soup',
  'salmon',
  'eggs',
  'gums',
  'tomato juice',
  'candy bars'],
 ['spaghetti', 'mineral water', 'chicken'],
 ['turkey', 'ground beef', 'carrots', 'french fries', 'melons'],
 ['mineral water', 'eggs', 'low fat yogurt'],
 ['turkey', 'cooking oil', 'shampoo'],
 ['spaghetti', 'hot dogs'],
 ['chocolate', 'green tea'],
 ['grated cheese',
  'pepper',
  'mineral water',
  'chocolate',
  'eggs',
  'cake',
  'mashed potato',
  'tomato juice'],
 ['chocolate'],
 ['spaghetti', 'olive oil', 'strong cheese', 'pancakes'],
 ['red wine', 'mineral water', 'soup', 'rice', 'cookies'],
 ['red wine', 'shrimp', 'spaghetti'],
 ['green tea'],
 ['mineral water', 'chicken', 'french fries', 'frozen smoothie'],
 ['muffins'],
 ['cake', 'chocolate'],
 ['fresh tuna',
  'tomatoes',
  'mineral water',
  'soup',
  'avocado',
  'meatballs',
  'olive oil'],
 ['turkey', 'french fries'],
 ['burgers',
  'turkey',
  'herb & pepper',
  'ground beef',
  'pancakes',
  'eggs',
  'light cream',
  'rice',
  'champagne',
  'fresh bread'],
 ['escalope'],
 ['chocolate', 'escalope', 'fresh bread'],
 ['ham',
  'spaghetti',
  'french wine',
  'vegetables mix',
  'chocolate',
  'french fries'],
 ['avocado', 'light mayo'],
 ['spaghetti', 'yams', 'butter', 'chocolate'],
 ['energy bar', 'eggs', 'french fries'],
 ['fresh tuna', 'barbecue sauce', 'eggplant'],
 ['energy drink'],
 ['whole wheat rice', 'french fries', 'hot dogs', 'green tea'],
 ['mineral water', 'chicken', 'green tea'],
 ['eggs', 'cake', 'mushroom cream sauce'],
 ['escalope'],
 ['antioxydant juice', 'escalope'],
 ['shrimp', 'spaghetti', 'french fries'],
 ['grated cheese', 'spaghetti', 'salmon', 'tomato juice'],
 ['spaghetti', 'green tea'],
 ['champagne', 'protein bar'],
 ['mineral water', 'avocado', 'chocolate'],
 ['tomatoes', 'champagne', 'green tea'],
 ['chicken', 'french fries', 'escalope'],
 ['frozen vegetables',
  'tomatoes',
  'eggs',
  'green tea',
  'frozen smoothie',
  'light mayo'],
 ['ground beef',
  'chicken',
  'cider',
  'green grapes',
  'honey',
  'chocolate',
  'french fries',
  'champagne',
  'frozen smoothie',
  'escalope'],
 ['french fries', 'champagne'],
 ['mineral water', 'soup'],
 ['frozen vegetables', 'spaghetti', 'milk', 'chocolate', 'babies food'],
 ['honey', 'whole wheat rice'],
 ['whole wheat rice', 'chicken', 'tomato juice'],
 ['pancakes'],
 ['green tea', 'protein bar', 'tomato juice', 'candy bars'],
 ['french fries'],
 ['mineral water'],
 ['escalope'],
 ['grated cheese',
  'herb & pepper',
  'whole wheat pasta',
  'yams',
  'mineral water',
  'bacon',
  'nonfat milk',
  'spinach'],
 ['spaghetti', 'milk'],
 ['milk', 'chocolate', 'white wine'],
 ['sandwich'],

In [31]:
te = TransactionEncoder()

te_array = te.fit(transactions).transform(transactions)

df = pd.DataFrame(te_array, columns = te.columns_)
df

,asparagus,almonds,antioxydant juice,asparagus,avocado,babies food,bacon,barbecue sauce,black tea,blueberries,...,turkey,vegetables mix,water spray,white wine,whole weat flour,whole wheat pasta,whole wheat rice,yams,yogurt cake,zucchini
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,True,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7495,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7496,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7497,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7498,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7499,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False

In [32]:
freq_items = apriori(df, min_support = 0.05, use_colnames = True)
freq_items

     support                               itemsets
0   0.087200                   frozenset({burgers})
1   0.081067                      frozenset({cake})
2   0.060000                   frozenset({chicken})
3   0.163867                 frozenset({chocolate})
4   0.080400                   frozenset({cookies})
5   0.051067               frozenset({cooking oil})
6   0.179733                      frozenset({eggs})
7   0.079333                  frozenset({escalope})
8   0.170933              frozenset({french fries})
9   0.063200           frozenset({frozen smoothie})
10  0.095333         frozenset({frozen vegetables})
11  0.052400             frozenset({grated cheese})
12  0.132000                 frozenset({green tea})
13  0.098267               frozenset({ground beef})
14  0.076400            frozenset({low fat yogurt})
15  0.129600                      frozenset({milk})
16  0.238267             frozenset({mineral water})
17  0.065733                 frozenset({olive oil})
18  0.095067                  frozenset({pancakes})
19  0.071333                    frozenset({shrimp})
20  0.050533                      frozenset({soup})
21  0.174133                 frozenset({spaghetti})
22  0.068400                  frozenset({tomatoes})
23  0.062533                    frozenset({turkey})
24  0.058533          frozenset({whole wheat rice})
25  0.052667  frozenset({mineral water, chocolate})
26  0.050933       frozenset({eggs, mineral water})
27  0.059733  frozenset({mineral water, spaghetti})

In [33]:
rules = association_rules(freq_items, metric = 'support', min_threshold = 0.05)
rules = rules.sort_values(['support', 'confidence'], ascending = [False, False])

rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
5,frozenset({spaghetti}),frozenset({mineral water}),0.174133,0.238267,0.059733,0.343032,1.439698,1.0,0.018243,1.159468,0.369806,0.169376,0.137536,0.296866
4,frozenset({mineral water}),frozenset({spaghetti}),0.238267,0.174133,0.059733,0.250699,1.439698,1.0,0.018243,1.102184,0.400941,0.169376,0.092710,0.296866
1,frozenset({chocolate}),frozenset({mineral water}),0.163867,0.238267,0.052667,0.321400,1.348907,1.0,0.013623,1.122506,0.309351,0.150706,0.109136,0.271220
0,frozenset({mineral water}),frozenset({chocolate}),0.238267,0.163867,0.052667,0.221041,1.348907,1.0,0.013623,1.073398,0.339566,0.150706,0.068379,0.271220
3,frozenset({eggs}),frozenset({mineral water}),0.179733,0.238267,0.050933,0.283383,1.189351,1.0,0.008109,1.062957,0.194090,0.138758,0.059228,0.248574
2,frozenset({mineral water}),frozenset({eggs}),0.238267,0.179733,0.050933,0.213766,1.189351,1.0,0.008109,1.043286,0.209004,0.138758,0.041490,0.248574

Slip 8

In [44]:
#   Download the groceries dataset. Write a python program to read the dataset and display its
#   information. Preprocess the data (drop null values etc.) Convert the categorical values into numeric
#   format. Apply the apriori algorithm on the above dataset to generate the frequent itemsets and association
#   rules.

data = pd.read_csv("groceries.csv")

data = data.drop('Member_number', axis = 1)
data = data.drop('Date', axis = 1)

data.info()

<class 'pandas.DataFrame'>
RangeIndex: 38765 entries, 0 to 38764
Data columns (total 1 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   itemDescription  38765 non-null  str
dtypes: str(1)
memory usage: 303.0 KB

In [45]:
transactions = []

for i in range(len(data)):
    row_item = []
    for j in range(len(data.columns)):
        val = data.values[i, j]

        if pd.notnull(val) and val != "":
            row_item.append(val)
    if len(row_item) > 0:
        transactions.append(row_item)

transactions

[['tropical fruit'],
 ['whole milk'],
 ['pip fruit'],
 ['other vegetables'],
 ['whole milk'],
 ['rolls/buns'],
 ['other vegetables'],
 ['pot plants'],
 ['whole milk'],
 ['tropical fruit'],
 ['citrus fruit'],
 ['beef'],
 ['frankfurter'],
 ['chicken'],
 ['butter'],
 ['fruit/vegetable juice'],
 ['packaged fruit/vegetables'],
 ['chocolate'],
 ['specialty bar'],
 ['other vegetables'],
 ['butter milk'],
 ['whole milk'],
 ['tropical fruit'],
 ['tropical fruit'],
 ['bottled water'],
 ['yogurt'],
 ['sausage'],
 ['other vegetables'],
 ['brown bread'],
 ['yogurt'],
 ['hamburger meat'],
 ['root vegetables'],
 ['pork'],
 ['beef'],
 ['pastry'],
 ['fruit/vegetable juice'],
 ['canned beer'],
 ['root vegetables'],
 ['citrus fruit'],
 ['sausage'],
 ['tropical fruit'],
 ['berries'],
 ['canned beer'],
 ['butter milk'],
 ['coffee'],
 ['pastry'],
 ['rolls/buns'],
 ['misc. beverages'],
 ['root vegetables'],
 ['sausage'],
 ['canned beer'],
 ['ham'],
 ['turkey'],
 ['whole milk'],
 ['whole milk'],
 ['packaged fruit/vegetables'],
 ['rolls/buns'],
 ['ham'],
 ['rolls/buns'],
 ['other vegetables'],
 ['sausage'],
 ['sausage'],
 ['frankfurter'],
 ['rolls/buns'],
 ['whole milk'],
 ['curd cheese'],
 ['red/blush wine'],
 ['sausage'],
 ['tropical fruit'],
 ['red/blush wine'],
 ['whole milk'],
 ['frankfurter'],
 ['whole milk'],
 ['frozen potato products'],
 ['other vegetables'],
 ['citrus fruit'],
 ['flour'],
 ['sugar'],
 ['frozen meals'],
 ['chocolate'],
 ['root vegetables'],
 ['root vegetables'],
 ['herbs'],
 ['bottled water'],
 ['sausage'],
 ['coffee'],
 ['pork'],
 ['berries'],
 ['soda'],
 ['berries'],
 ['fruit/vegetable juice'],
 ['citrus fruit'],
 ['pork'],
 ['detergent'],
 ['grapes'],
 ['sausage'],
 ['chicken'],
 ['whole milk'],
 ['citrus fruit'],
 ['soda'],
 ['sausage'],
 ['frankfurter'],
 ['sausage'],
 ['soda'],
 ['rolls/buns'],
 ['beef'],
 ['whole milk'],
 ['processed cheese'],
 ['tropical fruit'],
 ['frankfurter'],
 ['packaged fruit/vegetables'],
 ['whole milk'],
 ['berries'],
 ['citrus fruit'],
 ['tropical fruit'],
 ['hamburger meat'],
 ['hamburger meat'],
 ['whole milk'],
 ['fish'],
 ['frankfurter'],
 ['packaged fruit/vegetables'],
 ['pastry'],
 ['other vegetables'],
 ['misc. beverages'],
 ['frankfurter'],
 ['sparkling wine'],
 ['specialty bar'],
 ['sausage'],
 ['curd cheese'],
 ['frankfurter'],
 ['whole milk'],
 ['newspapers'],
 ['berries'],
 ['curd'],
 ['tropical fruit'],
 ['soda'],
 ['rolls/buns'],
 ['canned beer'],
 ['canned beer'],
 ['frankfurter'],
 ['other vegetables'],
 ['whole milk'],
 ['whole milk'],
 ['citrus fruit'],
 ['frankfurter'],
 ['frankfurter'],
 ['butter milk'],
 ['hamburger meat'],
 ['pasta'],
 ['other vegetables'],
 ['sausage'],
 ['rolls/buns'],
 ['grapes'],
 ['root vegetables'],
 ['coffee'],
 ['popcorn'],
 ['whole milk'],
 ['tropical fruit'],
 ['beef'],
 ['whole milk'],
 ['frankfurter'],
 ['tropical fruit'],
 ['canned beer'],
 ['finished products'],
 ['beverages'],
 ['hamburger meat'],
 ['whole milk'],
 ['finished products'],
 ['other vegetables'],
 ['ham'],
 ['other vegetables'],
 ['curd'],
 ['bottled beer'],
 ['curd'],
 ['whole milk'],
 ['whole milk'],
 ['dessert'],
 ['sausage'],
 ['other vegetables'],
 ['ham'],
 ['other vegetables'],
 ['other vegetables'],
 ['soda'],
 ['herbs'],
 ['frankfurter'],
 ['rolls/buns'],
 ['curd'],
 ['frankfurter'],
 ['other vegetables'],
 ['dog food'],
 ['specialty bar'],
 ['curd'],
 ['frankfurter'],
 ['soda'],
 ['beef'],
 ['canned beer'],
 ['pork'],
 ['frankfurter'],
 ['sausage'],
 ['canned beer'],
 ['specialty chocolate'],
 ['curd'],
 ['canned beer'],
 ['whole milk'],
 ['rolls/buns'],
 ['pork'],
 ['citrus fruit'],
 ['pot plants'],
 ['rolls/buns'],
 ['butter'],
 ['condensed milk'],
 ['sausage'],
 ['whole milk'],
 ['sausage'],
 ['beverages'],
 ['beverages'],
 ['bottled water'],
 ['newspapers'],
 ['cleaner'],
 ['sausage'],
 ['newspapers'],
 ['sausage'],
 ['misc. beverages'],
 ['white wine'],
 ['sausage'],
 ['meat'],
 ['frankfurter'],
 ['ice cream'],
 ['canned beer'],
 ['tropical fruit'],
 ['meat'],
 ['whole milk'],
 ['sausage'],
 ['frankfurter'],
 ['meat'],
 ['root vegetables'],
 ['root vegetables'],
 ['whole milk'],
 ['citrus fruit'],
 ['citrus fruit'],
 ['other vegetables'],
 ['citrus fruit'],
 ['sausage'],
 ['frankfurter'],
 ['hard cheese'],
 ['cream cheese '],
 ['turkey'],
 ['pork'],
 ['whole milk'],
 ['rolls/buns'],
 ['sausage'],
 ['ice cream'],
 ['liquor'],
 ['pip fruit'],
 ['root vegetables'],
 ['soda'],
 ['soda'],
 ['sausage'],
 ['root vegetables'],
 ['pork'],
 ['pork'],
 ['chocolate'],
 ['fruit/vegetable juice'],
 ['pickled vegetables'],
 ['bottled water'],
 ['frankfurter'],
 ['tropical fruit'],
 ['canned beer'],
 ['root vegetables'],
 ['meat'],
 ['frankfurter'],
 ['tropical fruit'],
 ['tropical fruit'],
 ['citrus fruit'],
 ['hamburger meat'],
 ['chicken'],
 ['chicken'],
 ['frankfurter'],
 ['canned beer'],
 ['turkey'],
 ['packaged fruit/vegetables'],
 ['pasta'],
 ['citrus fruit'],
 ['sausage'],
 ['whole milk'],
 ['canned beer'],
 ['citrus fruit'],
 ['liquor (appetizer)'],
 ['citrus fruit'],
 ['sausage'],
 ['chicken'],
 ['hamburger meat'],
 ['sausage'],
 ['beef'],
 ['citrus fruit'],
 ['UHT-milk'],
 ['candy'],
 ['newspapers'],
 ['beef'],
 ['sausage'],
 ['frankfurter'],
 ['canned beer'],
 ['bottled beer'],
 ['onions'],
 ['tropical fruit'],
 ['bottled water'],
 ['beef'],
 ['sausage'],
 ['hair spray'],
 ['chicken'],
 ['pork'],
 ['ice cream'],
 ['meat'],
 ['other vegetables'],
 ['bottled water'],
 ['tropical fruit'],
 ['photo/film'],
 ['sausage'],
 ['grapes'],
 ['domestic eggs'],
 ['rolls/buns'],
 ['tropical fruit'],
 ['chicken'],
 ['frankfurter'],
 ['berries'],
 ['margarine'],
 ['tropical fruit'],
 ['ham'],
 ['hamburger meat'],
 ['yogurt'],
 ['soda'],
 ['yogurt'],
 ['soda'],
 ['bottled water'],
 ['sausage'],
 ['citrus fruit'],
 ['shopping bags'],
 ['newspapers'],
 ['frankfurter'],
 ['sausage'],
 ['frankfurter'],
 ['salt'],
 ['oil'],
 ['curd'],
 ['other vegetables'],
 ['citrus fruit'],
 ['frankfurter'],
 ['root vegetables'],
 ['tropical fruit'],
 ['beef'],
 ['berries'],
 ['canned beer'],
 ['whipped/sour cream'],
 ['root vegetables'],
 ['whole milk'],
 ['beef'],
 ['frozen vegetables'],
 ['rolls/buns'],
 ['whole milk'],
 ['whole milk'],
 ['citrus fruit'],
 ['pastry'],
 ['frankfurter'],
 ['tropical fruit'],
 ['frankfurter'],
 ['berries'],
 ['rolls/buns'],
 ['root vegetables'],
 ['yogurt'],
 ['other vegetables'],
 ['berries'],
 ['berries'],
 ['other vegetables'],
 ['rolls/buns'],
 ['ham'],
 ['whole milk'],
 ['tropical fruit'],
 ['bottled water'],
 ['butter milk'],
 ['newspapers'],
 ['coffee'],
 ['bottled beer'],
 ['onions'],
 ['hamburger meat'],
 ['sausage'],
 ['hard cheese'],
 ['sausage'],
 ['hamburger meat'],
 ['onions'],
 ['coffee'],
 ['shopping bags'],
 ['yogurt'],
 ['soda'],
 ['sliced cheese'],
 ['sausage'],
 ['yogurt'],
 ['domestic eggs'],
 ['whole milk'],
 ['meat'],
 ['dish cleaner'],
 ['other vegetables'],
 ['whole milk'],
 ['other vegetables'],
 ['tropical fruit'],
 ['baking powder'],
 ['specialty bar'],
 ['ice cream'],
 ['frankfurter'],
 ['canned beer'],
 ['bottled water'],
 ['other vegetables'],
 ['citrus fruit'],
 ['sausage'],
 ['domestic eggs'],
 ['pork'],
 ['specialty cheese'],
 ['pork'],
 ['beef'],
 ['other vegetables'],
 ['chicken'],
 ['soda'],
 ['whole milk'],
 ['rolls/buns'],
 ['bottled beer'],
 ['root vegetables'],
 ['pastry'],
 ['berries'],
 ['citrus fruit'],
 ['whole milk'],
 ['soda'],
 ['bottled water'],
 ['tropical fruit'],
 ['salty snack'],
 ['bottled water'],
 ['chocolate'],
 ['citrus fruit'],
 ['bottled water'],
 ['onions'],
 ['dessert'],
 ['beef'],
 ['rolls/buns'],
 ['beef'],
 ['soda'],
 ['coffee'],
 ['rolls/buns'],
 ['pork'],
 ['soda'],
 ['sausage'],
 ['beef'],
 ['whole milk'],
 ['pork'],
 ['berries'],
 ['sausage'],
 ['bottled water'],
 ['tropical fruit'],
 ['herbs'],
 ['yogurt'],
 ['Instant food products'],
 ['specialty chocolate'],
 ['coffee'],
 ['bottled beer'],
 ['beef'],
 ['whole milk'],
 ['frankfurter'],
 ['frankfurter'],
 ['other vegetables'],
 ['frankfurter'],
 ['whole milk'],
 ['frankfurter'],
 ['other vegetables'],
 ['bottled water'],
 ['pork'],
 ['bottled water'],
 ['other vegetables'],
 ['hamburger meat'],
 ['hamburger meat'],
 ['shopping bags'],
 ['whole milk'],
 ['ice cream'],
 ['pastry'],
 ['ham'],
 ['frankfurter'],
 ['sausage'],
 ['bottled beer'],
 ['bottled water'],
 ['meat'],
 ['dessert'],
 ['other vegetables'],
 ['beverages'],
 ['ham'],
 ['specialty bar'],
 ['brown bread'],
 ['whole milk'],
 ['rolls/buns'],
 ['bottled beer'],
 ['pet care'],
 ['citrus fruit'],
 ['pork'],
 ['other vegetables'],
 ['white wine'],
 ['whole milk'],
 ['pip fruit'],
 ['sugar'],
 ['tropical fruit'],
 ['root vegetables'],
 ['soda'],
 ['whole milk'],
 ['tropical fruit'],
 ['white bread'],
 ['brown bread'],
 ['tropical fruit'],
 ['domestic eggs'],
 ['coffee'],
 ['soda'],
 ['whole milk'],
 ['bottled beer'],
 ['pork'],
 ['other vegetables'],
 ['yogurt'],
 ['sparkling wine'],
 ['bottled water'],
 ['citrus fruit'],
 ['hamburger meat'],
 ['packaged fruit/vegetables'],
 ['other vegetables'],
 ['soda'],
 ['whole milk'],
 ['herbs'],
 ['citrus fruit'],
 ['misc. beverages'],
 ['female sanitary products'],
 ['soda'],
 ['tropical fruit'],
 ['soda'],
 ['white bread'],
 ['coffee'],
 ['tropical fruit'],
 ['pork'],
 ['citrus fruit'],
 ['frankfurter'],
 ['frankfurter'],
 ['frankfurter'],
 ['other vegetables'],
 ['yogurt'],
 ['sausage'],
 ['whole milk'],
 ['pip fruit'],
 ['whole milk'],
 ['root vegetables'],
 ['onions'],
 ['specialty chocolate'],
 ['hamburger meat'],
 ['photo/film'],
 ['rolls/buns'],
 ['canned beer'],
 ['canned beer'],
 ['other vegetables'],
 ['canned beer'],
 ['curd'],
 ['butter'],
 ['other vegetables'],
 ['whole milk'],
 ['beef'],
 ['sausage'],
 ['soda'],
 ['fruit/vegetable juice'],
 ['rolls/buns'],
 ['pip fruit'],
 ['frozen vegetables'],
 ['beverages'],
 ['hamburger meat'],
 ['root vegetables'],
 ['canned beer'],
 ['frozen vegetables'],
 ['canned beer'],
 ['newspapers'],
 ['rolls/buns'],
 ['hamburger meat'],
 ['pip fruit'],
 ['canned beer'],
 ['grapes'],
 ['root vegetables'],
 ['citrus fruit'],
 ['cling film/bags'],
 ['frankfurter'],
 ['whole milk'],
 ['pork'],
 ['chicken'],
 ['sausage'],
 ['specialty bar'],
 ['whipped/sour cream'],
 ['root vegetables'],
 ['rolls/buns'],
 ['other vegetables'],
 ['citrus fruit'],
 ['whole milk'],
 ['frankfurter'],
 ['coffee'],
 ['ham'],
 ['canned beer'],
 ['canned beer'],
 ['canned beer'],
 ['pip fruit'],
 ['pork'],
 ['soap'],
 ['pip fruit'],
 ['beef'],
 ['sausage'],
 ['frozen chicken'],
 ['soda'],
 ['tropical fruit'],
 ['other vegetables'],
 ['beef'],
 ['meat'],
 ['meat'],
 ['bottled water'],
 ['rolls/buns'],
 ['pastry'],
 ['pork'],
 ['pip fruit'],
 ['beef'],
 ['beef'],
 ['rolls/buns'],
 ['citrus fruit'],
 ['meat'],
 ['beverages'],
 ['beef'],
 ['ham'],
 ['hamburger meat'],
 ['beef'],
 ['beef'],
 ['root vegetables'],
 ['citrus fruit'],
 ['yogurt'],
 ['tropical fruit'],
 ['frankfurter'],
 ['beef'],
 ['shopping bags'],
 ['canned beer'],
 ['rolls/buns'],
 ['other vegetables'],
 ['hamburger meat'],
 ['hamburger meat'],
 ['frankfurter'],
 ['bottled beer'],
 ['tropical fruit'],
 ['soda'],
 ['frankfurter'],
 ['chicken'],
 ['coffee'],
 ['whole milk'],
 ['margarine'],
 ['tropical fruit'],
 ['meat'],
 ['cream cheese '],
 ['newspapers'],
 ['rolls/buns'],
 ['citrus fruit'],
 ['whole milk'],
 ['frankfurter'],
 ['ham'],
 ['frankfurter'],
 ['sausage'],
 ['domestic eggs'],
 ['whole milk'],
 ['rolls/buns'],
 ['whole milk'],
 ['sausage'],
 ['curd'],
 ['bottled water'],
 ['beef'],
 ['frankfurter'],
 ['chicken'],
 ['sausage'],
 ['pork'],
 ['yogurt'],
 ['whole milk'],
 ['frankfurter'],
 ['beef'],
 ['pip fruit'],
 ['sausage'],
 ['pastry'],
 ['chicken'],
 ['root vegetables'],
 ['whole milk'],
 ['detergent'],
 ['rolls/buns'],
 ['house keeping products'],
 ['yogurt'],
 ['tropical fruit'],
 ['tropical fruit'],
 ['curd'],
 ['beef'],
 ['whole milk'],
 ['pork'],
 ['other vegetables'],
 ['rolls/buns'],
 ['frankfurter'],
 ['yogurt'],
 ['whole milk'],
 ['bottled water'],
 ['frankfurter'],
 ['rolls/buns'],
 ['whole milk'],
 ['rolls/buns'],
 ['chicken'],
 ['tropical fruit'],
 ['sausage'],
 ['sausage'],
 ['frankfurter'],
 ['UHT-milk'],
 ['rolls/buns'],
 ['canned beer'],
 ['yogurt'],
 ['whipped/sour cream'],
 ['rolls/buns'],
 ['rolls/buns'],
 ['beverages'],
 ['rolls/buns'],
 ['rolls/buns'],
 ['bottled beer'],
 ['citrus fruit'],
 ['bottled water'],
 ['pastry'],
 ['domestic eggs'],
 ['beef'],
 ['spread cheese'],
 ['tropical fruit'],
 ['packaged fruit/vegetables'],
 ['whole milk'],
 ['meat'],
 ['onions'],
 ['frankfurter'],
 ['beef'],
 ['beef'],
 ['sausage'],
 ['chicken'],
 ['canned beer'],
 ['sausage'],
 ['tropical fruit'],
 ['frankfurter'],
 ['sausage'],
 ['beef'],
 ['tropical fruit'],
 ['yogurt'],
 ['frankfurter'],
 ['bottled beer'],
 ['grapes'],
 ['beverages'],
 ['curd'],
 ['ice cream'],
 ['sausage'],
 ['other vegetables'],
 ['dessert'],
 ['decalcifier'],
 ['canned beer'],
 ['coffee'],
 ['berries'],
 ['pork'],
 ['frankfurter'],
 ['pork'],
 ['frankfurter'],
 ['frozen dessert'],
 ['chicken'],
 ['vinegar'],
 ['rolls/buns'],
 ['whole milk'],
 ['pork'],
 ['rolls/buns'],
 ['grapes'],
 ['frankfurter'],
 ['finished products'],
 ['onions'],
 ['tropical fruit'],
 ['other vegetables'],
 ['ham'],
 ['other vegetables'],
 ['curd'],
 ['sausage'],
 ['canned beer'],
 ['ham'],
 ['packaged fruit/vegetables'],
 ['meat'],
 ['whole milk'],
 ['canned beer'],
 ['chicken'],
 ['rolls/buns'],
 ['pet care'],
 ['root vegetables'],
 ['pastry'],
 ['frankfurter'],
 ['chicken'],
 ['frozen dessert'],
 ['citrus fruit'],
 ['sausage'],
 ['root vegetables'],
 ['root vegetables'],
 ['bottled beer'],
 ['frankfurter'],
 ['root vegetables'],
 ['berries'],
 ['hamburger meat'],
 ['tropical fruit'],
 ['frankfurter'],
 ['frankfurter'],
 ['soda'],
 ['ice cream'],
 ['beef'],
 ['whole milk'],
 ['pork'],
 ['whole milk'],
 ['bottled beer'],
 ['pork'],
 ['root vegetables'],
 ['canned beer'],
 ['citrus fruit'],
 ['pip fruit'],
 ['root vegetables'],
 ['tropical fruit'],
 ['beef'],
 ['chicken'],
 ['citrus fruit'],
 ['meat'],
 ['cream cheese '],
 ['citrus fruit'],
 ['specialty bar'],
 ['meat'],
 ['citrus fruit'],
 ['frankfurter'],
 ['citrus fruit'],
 ['turkey'],
 ['citrus fruit'],
 ['sausage'],
 ['newspapers'],
 ['whole milk'],
 ['yogurt'],
 ['yogurt'],
 ['bottled water'],
 ['berries'],
 ['packaged fruit/vegetables'],
 ['frankfurter'],
 ['nuts/prunes'],
 ['citrus fruit'],
 ['beef'],
 ['whole milk'],
 ['other vegetables'],
 ['beef'],
 ['fish'],
 ['other vegetables'],
 ['tropical fruit'],
 ['coffee'],
 ['sausage'],
 ['meat'],
 ['chicken'],
 ['berries'],
 ['frozen meals'],
 ['whipped/sour cream'],
 ['beef'],
 ['chicken'],
 ['chicken'],
 ['beef'],
 ['packaged fruit/vegetables'],
 ['sugar'],
 ['frankfurter'],
 ['berries'],
 ['bottled water'],
 ['sausage'],
 ['whole milk'],
 ['ice cream'],
 ['frankfurter'],
 ['root vegetables'],
 ['sausage'],
 ['sausage'],
 ['beef'],
 ['fruit/vegetable juice'],
 ['sugar'],
 ['berries'],
 ['yogurt'],
 ['pork'],
 ['bottled beer'],
 ['curd'],
 ['beef'],
 ['pork'],
 ['white bread'],
 ['grapes'],
 ['potato products'],
 ['root vegetables'],
 ['chicken'],
 ['chicken'],
 ['fish'],
 ['canned beer'],
 ['other vegetables'],
 ['chicken'],
 ['other vegetables'],
 ['tropical fruit'],
 ['whole milk'],
 ['beef'],
 ['sausage'],
 ['whole milk'],
 ['rolls/buns'],
 ['citrus fruit'],
 ['whole milk'],
 ['pastry'],
 ['tropical fruit'],
 ['sliced cheese'],
 ['soda'],
 ['ham'],
 ['salty snack'],
 ['whole milk'],
 ['root vegetables'],
 ['soda'],
 ['curd'],
 ['bottled water'],
 ['packaged fruit/vegetables'],
 ['tropical fruit'],
 ['ham'],
 ['pork'],
 ['beverages'],
 ['sausage'],
 ['sausage'],
 ['root vegetables'],
 ['whole milk'],
 ['frankfurter'],
 ['soda'],
 ['soda'],
 ['frankfurter'],
 ['berries'],
 ['canned beer'],
 ['frankfurter'],
 ['frankfurter'],
 ['berries'],
 ['frankfurter'],
 ['newspapers'],
 ['frozen fish'],
 ['tropical fruit'],
 ['beef'],
 ['rolls/buns'],
 ['specialty chocolate'],
 ['sparkling wine'],
 ['citrus fruit'],
 ['onions'],
 ['whole milk'],
 ['photo/film'],
 ['hamburger meat'],
 ['other vegetables'],
 ['whole milk'],
 ['pork'],
 ['tropical fruit'],
 ['chicken'],
 ['other vegetables'],
 ['sausage'],
 ['whole milk'],
 ['rolls/buns'],
 ['hygiene articles'],
 ['ice cream'],
 ['curd'],
 ['whole milk'],
 ['onions'],
 ['finished products'],
 ['salt'],
 ['tropical fruit'],
 ['other vegetables'],
 ['chocolate'],
 ['ice cream'],
 ['tropical fruit'],
 ['frankfurter'],
 ['butter'],
 ['other vegetables'],
 ['tropical fruit'],
 ['citrus fruit'],
 ['UHT-milk'],
 ['beef'],
 ['curd'],
 ['citrus fruit'],
 ['yogurt'],
 ['bottled beer'],
 ['grapes'],
 ['pork'],
 ['sausage'],
 ['frankfurter'],
 ['artif. sweetener'],
 ['frankfurter'],
 ['pip fruit'],
 ['frankfurter'],
 ['whole milk'],
 ['domestic eggs'],
 ['packaged fruit/vegetables'],
 ['chicken'],
 ['pork'],
 ['citrus fruit'],
 ['light bulbs'],
 ['cream cheese '],
 ['sausage'],
 ['citrus fruit'],
 ['other vegetables'],
 ['chicken'],
 ['ice cream'],
 ['pork'],
 ['pork'],
 ['onions'],
 ...]

In [46]:
te = TransactionEncoder()

te_array = te.fit(transactions).transform(transactions)

df = pd.DataFrame(te_array, columns = te.columns_)
df

,Instant food products,UHT-milk,abrasive cleaner,artif. sweetener,baby cosmetics,bags,baking powder,bathroom cleaner,beef,berries,...,turkey,vinegar,waffles,whipped/sour cream,whisky,white bread,white wine,whole milk,yogurt,zwieback
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38760,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
38761,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
38762,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
38763,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
38764,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [67]:
freq_items = apriori(df, min_support = 0.001, use_colnames = True)
freq_items

      support                            itemsets
0    0.001548  frozenset({Instant food products})
1    0.008332               frozenset({UHT-milk})
2    0.003147          frozenset({baking powder})
3    0.013311                   frozenset({beef})
4    0.008435                frozenset({berries})
..        ...                                 ...
111  0.009338            frozenset({white bread})
112  0.004540             frozenset({white wine})
113  0.064543             frozenset({whole milk})
114  0.034412                 frozenset({yogurt})
115  0.001548               frozenset({zwieback})

[116 rows x 2 columns]

In [68]:
rules = association_rules(freq_items, metric = 'support', min_threshold = 0.05)
rules = rules.sort_values(['support', 'confidence'], ascending = [False, False])

rules

Empty DataFrame
Columns: [antecedents, consequents, antecedent support, consequent support, support, confidence, lift, representativity, leverage, conviction, zhangs_metric, jaccard, certainty, kulczynski]
Index: []

Slip 10

In [99]:
#   Create the following dataset in python & Convert the categorical values into numeric format. Apply
#   the apriori algorithm on the above dataset to generate the frequent itemsets and association rules. Repeat
#   the process with different min_sup values.

transactions =   [   ['eggs', 'milk','bread'],
                    ['eggs', 'apple'],
                    ['milk', 'bread'],
                    ['apple', 'milk'],
                    ['milk', 'apple', 'bread']
                ]

te = TransactionEncoder()

te_array = te.fit(transactions).transform(transactions)


df = pd.DataFrame(te_array, columns = te.columns_)

freq_items = apriori(df, min_support = 0.05, use_colnames = True)
freq_items

    support                         itemsets
0       0.6               frozenset({apple})
1       0.6               frozenset({bread})
2       0.4                frozenset({eggs})
3       0.8                frozenset({milk})
4       0.2        frozenset({bread, apple})
5       0.2         frozenset({eggs, apple})
6       0.4         frozenset({milk, apple})
7       0.2         frozenset({eggs, bread})
8       0.6         frozenset({milk, bread})
9       0.2          frozenset({milk, eggs})
10      0.2  frozenset({milk, bread, apple})
11      0.2   frozenset({milk, eggs, bread})

In [101]:
rules = association_rules(freq_items, metric = 'support', min_threshold = 0.05)
rules = rules.sort_values(['support', 'confidence'], ascending = [False, False])

rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
9,frozenset({bread}),frozenset({milk}),0.6,0.8,0.6,1.000000,1.250000,1.0,0.12,inf,0.500000,0.750000,1.000000,0.875000
8,frozenset({milk}),frozenset({bread}),0.8,0.6,0.6,0.750000,1.250000,1.0,0.12,1.600000,1.000000,0.750000,0.375000,0.875000
5,frozenset({apple}),frozenset({milk}),0.6,0.8,0.4,0.666667,0.833333,1.0,-0.08,0.600000,-0.333333,0.400000,-0.666667,0.583333
4,frozenset({milk}),frozenset({apple}),0.8,0.6,0.4,0.500000,0.833333,1.0,-0.08,0.800000,-0.500000,0.400000,-0.250000,0.583333
14,"frozenset({bread, apple})",frozenset({milk}),0.2,0.8,0.2,1.000000,1.250000,1.0,0.04,inf,0.250000,0.250000,1.000000,0.625000
18,"frozenset({milk, eggs})",frozenset({bread}),0.2,0.6,0.2,1.000000,1.666667,1.0,0.08,inf,0.500000,0.333333,1.000000,0.666667
20,"frozenset({eggs, bread})",frozenset({milk}),0.2,0.8,0.2,1.000000,1.250000,1.0,0.04,inf,0.250000,0.250000,1.000000,0.625000
2,frozenset({eggs}),frozenset({apple}),0.4,0.6,0.2,0.500000,0.833333,1.0,-0.04,0.800000,-0.250000,0.250000,-0.250000,0.416667
6,frozenset({eggs}),frozenset({bread}),0.4,0.6,0.2,0.500000,0.833333,1.0,-0.04,0.800000,-0.250000,0.250000,-0.250000,0.416667
11,frozenset({eggs}),frozenset({milk}),0.4,0.8,0.2,0.500000,0.625000,1.0,-0.12,0.400000,-0.500000,0.200000,-1.500000,0.375000
13,"frozenset({milk, apple})",frozenset({bread}),0.4,0.6,0.2,0.500000,0.833333,1.0,-0.04,0.800000,-0.250000,0.250000,-0.250000,0.416667
22,frozenset({eggs}),"frozenset({milk, bread})",0.4,0.6,0.2,0.500000,0.833333,1.0,-0.04,0.800000,-0.250000,0.250000,-0.250000,0.416667
0,frozenset({bread}),frozenset({apple}),0.6,0.6,0.2,0.333333,0.555556,1.0,-0.16,0.600000,-0.666667,0.200000,-0.666667,0.333333
1,frozenset({apple}),frozenset({bread}),0.6,0.6,0.2,0.333333,0.555556,1.0,-0.16,0.600000,-0.666667,0.200000,-0.666667,0.333333
3,frozenset({apple}),frozenset({eggs}),0.6,0.4,0.2,0.333333,0.833333,1.0,-0.04,0.900000,-0.333333,0.250000,-0.111111,0.416667
7,frozenset({bread}),frozenset({eggs}),0.6,0.4,0.2,0.333333,0.833333,1.0,-0.04,0.900000,-0.333333,0.250000,-0.111111,0.416667
12,"frozenset({milk, bread})",frozenset({apple}),0.6,0.6,0.2,0.333333,0.555556,1.0,-0.16,0.600000,-0.666667,0.200000,-0.666667,0.333333
16,frozenset({bread}),"frozenset({milk, apple})",0.6,0.4,0.2,0.333333,0.833333,1.0,-0.04,0.900000,-0.333333,0.250000,-0.111111,0.416667
17,frozenset({apple}),"frozenset({milk, bread})",0.6,0.6,0.2,0.333333,0.555556,1.0,-0.16,0.600000,-0.666667,0.200000,-0.666667,0.333333
19,"frozenset({milk, bread})",frozenset({eggs}),0.6,0.4,0.2,0.333333,0.833333,1.0,-0.04,0.900000,-0.333333,0.250000,-0.111111,0.416667
23,frozenset({bread}),"frozenset({milk, eggs})",0.6,0.2,0.2,0.333333,1.666667,1.0,0.08,1.200000,1.000000,0.333333,0.166667,0.666667
10,frozenset({milk}),frozenset({eggs}),0.8,0.4,0.2,0.250000,0.625000,1.0,-0.12,0.800000,-0.750000,0.200000,-0.250000,0.375000
15,frozenset({milk}),"frozenset({bread, apple})",0.8,0.2,0.2,0.250000,1.250000,1.0,0.04,1.066667,1.000000,0.250000,0.062500,0.625000
21,frozenset({milk}),"frozenset({eggs, bread})",0.8,0.2,0.2,0.250000,1.250000,1.0,0.04,1.066667,1.000000,0.250000,0.062500,0.625000